import type { Metadata } from 'next';
import ErrorWrapper from './error-wrapper';
import './globals.css';

export const metadata: Metadata = {
  title: {
    default: 'Next.js Tutorial Codevolution',
    template: '%s | Codevolution',
  },
  description: 'Generated by create next app',
};

const RootLayout = ({
  children
}: {
  children: React.ReactNode
}) => {
  return (
    <html lang='en'>
      <body>
        <div>
          <header className='bg-gray-100 text-black p-2'>
            this is root header
          </header>

          <ErrorWrapper>
            {children}
          </ErrorWrapper>

          <footer className='bg-gray-100 text-black p-2'>
            this is root footer
          </footer>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;