import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Routing Demo',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children
}: {
  children: React.ReactNode
}) => {
  return (
    <html lang='en'>
      <body>
        <div>
          <h2>This is root layout</h2>
          <header>this is root header</header>
          {children}
          <footer>this is root footer</footer>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;