import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Routing Demo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <header>This is header</header>
        {children}
        <footer>This is footer</footer>
      </body>
    </html>
  );
};
