import type { Metadata } from 'next';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Routing Demo',
  description: 'Generated by create next app',
};

const AuthLayout = ({
  children
}: {
  children: React.ReactNode
}) => {
  return (
    <html lang='en'>
      <body>
        <div>
          <h2>This is auth layout</h2>
          <header>this is auth header</header>
          {children}
          <footer>this is auth footer</footer>
        </div>
      </body>
    </html>
  );
};

export default AuthLayout;